### ISSUE TITLE
Trouble building BitThunder

### ISSUE THREAD

**Issue by sallman** [jameswalmsley/bitthunder#40]
Hello, James,

Sorry to trouble you but our project is in need of an RTOS running on the Raspberry Pi.

BitThunder or BootThunder look like they will fit the bill.  However, we have had some troubles just building the toolset. So, we were poised to post our situation and questions on a forum in hopes of some relief.  Alas, the links (some of them) are rejected with a 404 error.

Is there a place to post simple, newbie questions about BitThunder or BootThunder?

Kind regards,
S.M.Allman

**Comment by jameswalmsley** [comment]
Hi,

Sorry for not responding so quickly.
Please find an excellent tutorial from Richard Weiss under:

http://blog.richardweiss.org/2015/06/27/raspberry-pi-bitthunder.html

Post back with any other queries you may have and I'll try to assist.

James
